#ifndef __H_ACCELERATORS_H__
#define __H_ACCELERATORS_H__

#define USE_ACCEL_ERODE		1 << 3
#define USE_ACCEL_DILATE	1 << 4
#define USE_ACCEL_ALL		USE_ACCEL_ERODE | USE_ACCEL_DILATE
#define USE_ACCEL_NONE		0

#endif
